name: Integration tests

on:
  push:
    branches: ['develop', 'master']
  pull_request:
    branches: ['develop', 'master']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: ./build-image.sh
      - name: Run tests
        run: |
          docker-compose up -d
          sleep 20
          ./test.sh
      - name: Dunp logs
        if: always()
        run: |
          docker ps
          find .
          docker container ls
          docker container ls --format '{{.ID}}' | xargs -t -n 1 docker logs